spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daraja?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

mpesa:
  daraja:
    consumer-key: vFOdO2mgqmLIKRc0QXmODMyQPYoTwMt4AYOVfpJG9Xu8Sd14
    consumer-secret: CiiPpkz4z8housn4TUR1XmZto1oTsrAvKVuG2miC7fnQyXTBjp6j8Up25RaQAR88
    passkey: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
    business-shortcode: 174379
    stk-push-callback-url: https://f63e16c9e62e.ngrok-free.app/api/payments/callback
    stk-push-url: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
    responseType: Completed
    shortCode: 600998
    confirmation-url: https://f63e16c9e62e.ngrok-free.app/api/payments/confirmation
    validation-url: https://f63e16c9e62e.ngrok-free.app/api/payments/validation
    register-url-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl
    simulate-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate
