spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daraja?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

mpesa:
  daraja:
    consumer-key: ${MPESA_CONSUMER_KEY}
    consumer-secret: ${MPESA_CONSUMER_SECRET}
    passkey: ${MPESA_PASSKEY}
    business-shortcode: ${MPESA_BUSINESS_SHORTCODE}
    stk-push-callback-url: ${MPESA_STK_PUSH_CALLBACK_URL}
    stk-push-url: ${MPESA_STK_PUSH_URL}
    responseType: ${MPESA_RESPONSE_TYPE:Completed}   # default value
    shortCode: ${MPESA_SHORT_CODE}
    confirmation-url: ${MPESA_CONFIRMATION_URL}
    validation-url: ${MPESA_VALIDATION_URL}
    register-url-endpoint: ${MPESA_REGISTER_URL}
    simulate-transaction-endpoint: ${MPESA_SIMULATE_URL}
    b2c-initiator-password: ${MPESA_B2C_INITIATOR_PASSWORD}
    b2c-result-url: ${MPESA_B2C_RESULT_URL}
    b2c-queue-timeout-url: ${MPESA_B2C_QUEUE_TIMEOUT_URL}
    b2c-initiator-name: ${MPESA_B2C_INITIATOR_NAME}
    b2c-transaction-endpoint: ${MPESA_B2C_TRANSACTION_URL}
    transactionResultUrl: ${MPESA_TRANSACTION_RESULT_URL}
    checkAccountBalanceUrl: ${MPESA_CHECK_BALANCE_URL}
    security-credential: ${MPESA_SECURITY_CREDENTIAL}
